# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_answers_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to='tests.Test'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to=settings.AUTH_USER_MODEL),
        ),
    ]
